version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=YLab
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password


  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=YLab

#    volumes:
#      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-db: