version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=YLab
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=YLab
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - CACHE_EXPIRE=60

volumes:
  postgres-db:
